language: cpp

compiler:
  - gcc

before_install:
  - pip install --user cpp-coveralls
  
install:
  - mkdir -p build
  - cd build 
  - cmake -D CMAKE_BUILD_TYPE=Debug -DCOVERAGE=1 ..
  - make
  - cd ..

script: 
  - build/run_tests
  
after_success:
  - coveralls  --root . --build-root "build/" -i "src/" -i "include/"
